# Variables
min_resposive = 750
alto_top_background = $('.top-background').height()
margen_contenido = $('main').css('margin-top')


isMobile =
  Android: ->
    navigator.userAgent.match /Android/i
  BlackBerry: ->
    navigator.userAgent.match /BlackBerry/i
  iOS: ->
    navigator.userAgent.match /iPhone|iPad|iPod/i
  Opera: ->
    navigator.userAgent.match /Opera Mini/i
  Windows: ->
    navigator.userAgent.match /IEMobile/i
  any: ->
    !isEmpty(navigator.userAgent.match(/mobi/i))

isEmpty = (str) ->
  typeof str == 'string' and !str.trim() or typeof str == 'undefined' or str == null

readURL = (input) ->
  if input.files and input.files[0]
    reader = new FileReader

    reader.onload = (e) ->
      $('#bic-foto').attr 'src', e.target.result
      return

    reader.readAsDataURL input.files[0]
  return

setCookie = (cname, cvalue, exdays) ->
  d = new Date
  d.setTime d.getTime() + exdays * 24 * 60 * 60 * 1000
  expires = 'expires=' + d.toUTCString()
  document.cookie = cname + '=' + cvalue + '; ' + expires
  return

getCookie = (cname) ->
  name = cname + '='
  ca = document.cookie.split(';')
  i = 0
  while i < ca.length
    c = ca[i]
    while c.charAt(0) == ' '
      c = c.substring(1)
    if c.indexOf(name) == 0
      return c.substring(name.length, c.length)
    i++
  ''

ajustar_elementos_web = ->
  win = $(this)
  if isEmpty($('.app-home-panel').html())
    if win.width() < min_resposive
      $('.alias-usuario').hide()
    else
      $('.alias-usuario').show()
  return

ocultar_menu = ->
  $('.menu-controlador').toggleClass 'closed'
  $('.btn-menu').html ''
  if $('.menu-controlador').hasClass('closed')
    $('.sobre-contenido-controlador').hide()
    $('.btn-menu').fadeIn(100).html '<i class="fa fa-bars fa-fw"></i>'
    $('main').unbind()
  else
    $('main').click ocultar_menu
    $('.sobre-contenido-controlador').show()
    $('.btn-menu').fadeIn(100).html '<i class="fa fa-times fa-fw"></i>'
  return

$(document).on 'ready page:load', ->
  $('.btn-menu').click ocultar_menu
  # Activar tooltips
  $('[data-toggle="tooltip"]').tooltip()
  # Eventos
  $(window).on 'resize', ajustar_elementos_web

  # gancho_menu_controlador();
  ajustar_elementos_web()

  # ###########################################################################
  # Centrar mapa cuando se cierra el infoWindow
  if $('#map').hasClass('centrar-cerrar-iw')
    centrarMapa = false
    MutationObserver = window.MutationObserver or window.WebKitMutationObserver
    observer = new MutationObserver((mutations, observer) ->
      if !isEmpty($('.gm-style-iw').text()) and !centrarMapa
        $('#map').click ->
          if isEmpty($('.gm-style-iw').text())
            handler.fitMapToBounds()
            $('#map').unbind()
            centrarMapa = false
          return
        centrarMapa = true
      return
)
    # handler.fitMapToBounds();
    # define what element should be observed by the observer
    # and what types of mutations trigger the callback
    observer.observe document.getElementById('map'),
      subtree: true
      attributes: true
  # ###########################################################################

  $('#imgInp').change ->
    readURL this
    return

  # $('input[type=file]').bootstrapFileInput();

  $('.datepicker').datepicker(dateFormat: 'dd-mm-yy')
  
  # $('.datepicker').change ->
  #   $('.datepicker').datepicker 'option', 'dateFormat', 'DD, d MM, yy'
  #   return
  $('.attachinary-input').attachinary()
  $('.attachinary_container').change ->
    alert ''
    $('.att-btn-eliminar').html '<%= t(\'destroy\') %>'
    return
  return

# ---
# generated by js2coffee 2.2.0
